"""Add GCS path to Tenant model

Revision ID: 121535b54ead
Revises: dffb7503b47a
Create Date: 2024-12-01 22:13:30.781903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121535b54ead'
down_revision = 'dffb7503b47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gcs_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('gcs_path')

    # ### end Alembic commands ###