"""Increase password_hash length

Revision ID: 7ec52113e82f
Revises: 121535b54ead
Create Date: 2024-12-03 09:23:20.376029

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ec52113e82f"
down_revision = "121535b54ead"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
